[package]
name = "ze-reflection"
version = "0.1.0"
edition = "2021"

[dependencies]
ze-reflection-derive = { version = "0.1.0", path = "../ze-reflection-derive" }
parking_lot = "0.12.1"
num-traits = "0.2.15"
num-derive = "0.3.3"
once_cell = "1.16.0"