[package]
name = "ze-d3dmemoryallocator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ze-d3dmemoryallocator-sys = { version = "0.1.0", path = "../ze-d3dmemoryallocator-sys" }
windows = { version = "0.43.0", features = [ "Win32_Graphics_Direct3D12", "Win32_Graphics_Direct3D", "Win32_Graphics_Dxgi" ] }
enumflags2 = "0.7.5"