[package]
name = "ze-metal-shader-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
ze-gfx = {path = "../../ze-gfx", version = "0.1.0" }
ze-filesystem = {path = "../../ze-filesystem", version = "0.1.0" }
ze-shader-compiler = {path = "../../ze-shader-compiler", version = "0.1.0" }