[package]
name = "ze-ecs-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.101"
quote = "1.0.21"
once_cell = "1.16.0"

[lib]
proc-macro = true