[package]
name = "ze-metal-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
ze-core = { version = "0.1.0", path = "../../ze-core" }
ze-gfx = { version = "0.1.0", path = "../../ze-gfx" }
metal = "0.24.0"