[package]
name = "ze_platform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ze_core = { version = "0.1.0", path = "../ze_core" }
enumflags2 = "0.7.5"
raw-window-handle = "0.4.3"