[package]
name = "zeassetc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.8", features = [ "derive" ] }
libloading = "0.7.3"
toml = "0.5.9"
serde = { version = "1.0.139", features = [ "derive" ] }