[package]
name = "ze-filesystem"
version = "0.1.0"
edition = "2021"

[dependencies]
ze-core = { version = "0.1.0", path = "../ze-core" }
parking_lot = "0.12.0"
notify = "4.0.17"
url = "2.2.2"
percent-encoding = "2.2.0"
enumflags2 = "0.7.5"