[package]
name = "ze-imgui-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "cimgui"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cmake = "0.1.48"
bindgen = "0.60.1"
cc = "1.0.73"
cfg-if = "1.0.0"