name: Build macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: nightly
        components: clippy
    - uses: Swatinem/rust-cache@v1 
    - name: Clippy
      run: cargo clippy --all-targets --no-deps
    - name: Build Editor
      run: cargo build --verbose --bin ze-editor --lib
    - name: Run tests
      run: cargo test --workspace --exclude ze-d3d12-backend
